name: Code Quality & Security Checks

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  sast-python:
    name: Run Bandit (SAST Security)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: bandit -r .

  lint-python:
    name: Run Ruff (Linter & Formatter)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3